steps:
  - id: 'terraform workspace select'
    name: 'alpine/terragrunt'
    args: ['terragrunt', 'run-all', 'workspace', 'select', '${_ENV}']
    env:
      - 'SKIP_OUTPUT=true'
      - 'TF_VAR_project=$PROJECT_ID'
      - 'ENV=${_ENV}'        

  - id: 'terragrunt destroy'
    name: 'alpine/terragrunt'
    args: ['terragrunt', 'run-all', 'destroy', '--terragrunt-non-interactive']
    env:
      - 'SKIP_OUTPUT=false'
      - 'TF_VAR_project=$PROJECT_ID'
      - 'ENV=${_ENV}'

substitutions:
  _ENV: prd
