steps:
  - id: 'create prd workspace'
    name: 'alpine/terragrunt'
    args: ['terragrunt', 'run-all', 'workspace', 'new', 'prd']
    env:
      - 'SKIP_OUTPUT=true'
      - 'TF_VAR_project=$PROJECT_ID'
      - 'ENV=prd'

  - id: 'delete gce/backend.tf @prd'
    name: 'ubuntu'
    args: ['rm', '-f', 'gce/backend.tf']

  - id: 'delete network/backend.tf @prd'
    name: 'ubuntu'
    args: ['rm', '-f', 'network/backend.tf']

  - id: 'create stg workspace'
    name: 'alpine/terragrunt'
    args: ['terragrunt', 'run-all', 'workspace', 'new', 'stg']
    env:
      - 'SKIP_OUTPUT=true'
      - 'TF_VAR_project=$PROJECT_ID'
      - 'ENV=stg'

  - id: 'delete gce/backend.tf @stg'
    name: 'ubuntu'
    args: ['rm', '-f', 'gce/backend.tf']

  - id: 'delete network/backend.tf @stg'
    name: 'ubuntu'
    args: ['rm', '-f', 'network/backend.tf']


  - id: 'create dev workspace'
    name: 'alpine/terragrunt'
    args: ['terragrunt', 'run-all', 'workspace', 'new', 'dev']
    env:
      - 'SKIP_OUTPUT=true'
      - 'TF_VAR_project=$PROJECT_ID'
      - 'ENV=dev'

  - id: 'delete gce/backend.tf @dev'
    name: 'ubuntu'
    args: ['rm', '-f', 'gce/backend.tf']

  - id: 'delete network/backend.tf @dev'
    name: 'ubuntu'
    args: ['rm', '-f', 'network/backend.tf']
